version: '3'

networks:
  default:
    name: guess_network

volumes:
  db_data: {}

services:
  app:
    build: .
    container_name: guess
    restart: always
    volumes:
      - ./:/home/guess
    ports:
      - "8030:8080"
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
      PHP_IDE_CONFIG: "serverName=guess-xdebug-docker"
    depends_on:
      - mysql

  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3386:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: guess
      MYSQL_USER: guess-admin
      MYSQL_PASSWORD: 321321
