version: '3'

networks:
  default:
    name: guess_network

volumes:
  db_data: {}

services:
  app:
    build: .
    container_name: guess
    restart: always
    volumes:
      - ./:/home/guess
    ports:
      - "8030:8080"
    depends_on:
      - mysql8

  mysql8:
    image: mysql:8.0
    container_name: mysql8
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: guess
      MYSQL_USER: guess-admin
      MYSQL_PASSWORD: 321321
